// Generates `dist/html-to-image-wasm.js`: the WASM binary compressed
// with gzip (level 9) and inlined as base64, so the browser worker bundle
// (`dist/web-workers.js`) embeds ~5MB instead of the 12MB SINGLE_FILE
// glue. Plain Node, no dependencies.
//
// Usage (from `packages/html-to-image/`):
//   node scripts/compress-wasm.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const wasmPath = join(root, "dist", "html-to-image.wasm");
const outPath = join(root, "dist", "html-to-image-wasm.js");

const raw = readFileSync(wasmPath);
const gz = gzipSync(raw, { level: 9 });
// NOTE: gzip only — `DecompressionStream` (W3C Compression Standard)
// accepts only "gzip"/"deflate"/"deflate-raw"; "br" is rejected by both
// browsers and Node (`not a valid enum value of type CompressionFormat`),
// so a brotli payload could never be restored at runtime.
const encoding = "gzip";
const base64 = gz.toString("base64");

writeFileSync(
  outPath,
  `// Generated by scripts/compress-wasm.mjs — do not edit.\n` +
    `export const wasmEncoding = ${JSON.stringify(encoding)};\n` +
    `export const wasmBase64 = ${JSON.stringify(base64)};\n`,
);

console.log(
  `raw=${raw.length} gzip=${gz.length} ` +
    `base64=${base64.length} encoding=${encoding} -> dist/html-to-image-wasm.js`,
);
