#ifndef SATORU_MASTER_CSS_H
#define SATORU_MASTER_CSS_H

const char* satoru_master_css =
    "html { display: block; margin: 0; padding: 0; }\n"
    "body { display: block; margin: 0; padding: 0; font-family: sans-serif;}\n"
    "p, dl, multicol, menu, ol, ul { display: block; margin-block-start: 1em; margin-block-end: "
    "1em; }\n"
    "dd { display: block; margin-inline-start: 40px; }\n"
    "ol, ul { padding-inline-start: 40px; }\n"
    "article, aside, footer, header, hgroup, main, nav, section { display: block; }\n"
    "blockquote { display: block; margin-block-start: 1em; margin-block-end: 1em; "
    "margin-inline-start: 40px; margin-inline-end: 40px; }\n"
    "figure { display: block; margin-block-start: 1em; margin-block-end: 1em; margin-inline-start: "
    "40px; margin-inline-end: 40px; }\n"
    "hr { display: block; margin-block-start: 0.5em; margin-block-end: 0.5em; margin-inline-start: "
    "auto; margin-inline-end: auto; border-style: inset; border-width: 1px; }\n"
    "pre { display: block; font-family: monospace; white-space: pre; margin-block-start: 1em; "
    "margin-block-end: 1em; }\n"
    "b, strong { font-weight: bold; }\n"
    "i, em { font-style: italic; }\n"
    "u { text-decoration: underline; }\n"
    "del, s { text-decoration: line-through; }\n"
    "sup { vertical-align: super; font-size: smaller; }\n"
    "sub { vertical-align: sub; font-size: smaller; }\n"
    "h1 { display: block; font-size: 2em; font-weight: bold; margin-block-start: 0.67em; "
    "margin-block-end: 0.67em; }\n"
    "h2 { display: block; font-size: 1.5em; font-weight: bold; margin-block-start: 0.83em; "
    "margin-block-end: 0.83em; }\n"
    "h3 { display: block; font-size: 1.17em; font-weight: bold; margin-block-start: 1em; "
    "margin-block-end: 1em; }\n"
    "h4 { display: block; font-size: 1em; font-weight: bold; margin-block-start: 1.33em; "
    "margin-block-end: 1.33em; }\n"
    "h5 { display: block; font-size: .83em; font-weight: bold; margin-block-start: 1.67em; "
    "margin-block-end: 1.67em; }\n"
    "h6 { display: block; font-size: .67em; font-weight: bold; margin-block-start: 2.33em; "
    "margin-block-end: 2.33em; }\n"
    "button {\n"
    "    display: inline-block;\n"
    "    text-align: center;\n"
    "    vertical-align: middle;\n"
    "    cursor: default;\n"
    "    box-sizing: border-box;\n"
    "    padding: 1px 6px;\n"
    "    border: 2px outset #767676;\n"
    "    background-color: #efefef;\n"
    "    color: #000;\n"
    "}\n"
    "button, input, select, textarea { box-sizing: border-box; }\n"
    "svg { display: inline-block; vertical-align: middle; overflow: hidden; }\n"
    "*[dir=\"rtl\"] { direction: rtl; }\n"
    "*[dir=\"ltr\"] { direction: ltr; }\n"
    "head, title, meta, link, style, script, noscript { display: none; }\n";

#endif  // SATORU_MASTER_CSS_H
